[package]
name = "slicer"
version = "1.0.0"
authors = ["BJTMastermind <bjtmastermind@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.14"
zip = "0.5.13"
